---
- name: work with service facts
  hosts: all

  tasks:
    - name: gather service facts
      service_facts:

    - name: show running services
      debug:
        msg: "{{ ansible_facts.services | dict2items 
          | selectattr('value.state', '==', 'running') | items2dict }}"
