--
- hosts: vps3
  become: yes

  tasks:
  - name: Remove the user 'johnd'
    ansible.builtin.user:
      name: johnd
      state: absent
      remove: yes

#Note: remove: yes, is to remove the home directoy as well.