---
- name: Install system updates for AlmaLinux systems
      yum:
        name: '*'
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "AlmaLinux"

    - name: Install system updates for ubuntu systems
      apt:
        name: '*'
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution == "Ubuntu"