---
version: "3"
services:
  nginx:
    image: debian:bullseye-slim
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /nginx/html/:/var/www/html/
      - /nginx/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped



#CLI:
#docker run --name mynginx2 
#--mount type=bind source=/var/www,target=/usr/share/nginx/html,readonly 
#--mount type=bind,source=/var/nginx/conf,target=/etc/nginx/conf,readonly
#-p 80:80 
#-d nginx