---
version: "2"
services:
  wikijs:
    image: linuxserver/wikijs
    container_name: wikijs
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Winnipeg
    volumes:
      - /srv/WikiJS/config:/config
      - /srv/WikiJS/data:/data
    ports:
      - 8082:3000
    restart: unless-stopped