---
 
 - hosts: all
   become: true
   pre_tasks:
 
   - name: update repository index (AlmaLinux)
     tags: always
     dnf:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "AlmaLinux"
 
   - name: update repository index (Ubuntu)
     tags: always
     apt:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Ubuntu"
 
 - hosts: all
   become: true
   roles:
     - base
    
 - hosts: workstations
   become: true
   roles:
     - workstations
 
 - hosts: webservers
   become: true
   roles:
     - webservers
 
 - hosts: dbservers
   become: true
   roles:
     - dbservers
 
 - hosts: fileservers
   become: true
   roles:
     - fileservers