version: '2'

services:

  linuxserver-plex:
    container_name: plex
    restart: unless-stopped
    image: linuxserver/plex:latest
    environment: 
    - TZ=America/Winnipeg
    - PUID=1000
    - PGID=1000
    - VERSION=docker
    network_mode: host
    volumes:
    - /home/boyet/plex/plex_config:/config
    - /home/boyet/plex/movie:/data/movies
    - /home/boyet/plex/photo:/dat
    - /home/boyet/plex/transcode:/transcode