---
- name: Patch Linux
  include_tasks: patch_linux.yml
  when: os is match("AlmaLinux 9.1")
  #("rhel.*")

- name: Patch Windows
  include_tasks: patch_windows.yml
  when: os is match("windows.*") or os is match("2016.*")